JTB-3: commit
Soqoor/test-repo pull request #9
Opened 2023-05-23 10:39 UTC by Soqoor

2023-05-23 10:41 UTC, Soqoor commented
1

2023-05-23 10:42 UTC, rukos17 requested changes
Need to fix

2023-05-23 10:42 UTC, rukos17 commented on README.md
> +New row
Whats this?

2023-05-23 10:54 UTC, rukos17 reviewed
Ok for now

2023-05-23 10:54 UTC, rukos17 approved these changes
Ok approve

2023-05-23 10:55 UTC, rukos17 approved these changes
Sure approve

2023-05-23 10:56 UTC, rukos17 commented
Just comment

2023-05-23 10:57 UTC, rukos17 requested changes
Wait!

2023-05-23 11:10 UTC, rukos17 approved these changes
app ok

2023-05-23 11:13 UTC, rukos17 reviewed
rewiew with comment

2023-05-23 11:13 UTC, rukos17 commented on README.md
> +New row
New comment on row

2023-05-23 11:25 UTC, rukos17 reviewed
Commented text

2023-05-23 11:26 UTC, rukos17 requested changes
Need to fix

2023-05-23 11:29 UTC, rukos17 approved these changes

2023-08-28 12:40 UTC, Soqoor commented
123qwe

2023-09-14 07:47 UTC, closed without merging